### ISSUE TITLE
can't install generator-minecraft-addon

### ISSUE THREAD

**Issue by JinsX5** [minecraft-addon-tools/generator-minecraft-addon#2]
The cmd feedback is below:

C:\Users\pc>yo install -g generator-minecraft-addon
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== Yes
Error install -g generator-minecraft-addon

You don't seem to have a generator with the name “install” installed.

**Comment by JinsX5** [comment]
I solved it,its my command fault

**Comment by AtomicBlom** [comment]
Ah, sorry for the slow reply. I totally missed this. Glad you got it solved.
