### ISSUE TITLE
Update Typescript Types Version

### ISSUE THREAD

**Issue by dhkatz** [minecraft-addon-tools/generator-minecraft-addon#3]
The version of the Typescript types provided by the generator is out of date. This causes certain events being listened to in game to not work when using the enums (i.e ReceiveFromMinecraftServer.PlayerAttackedActor is now ReceiveFromMinecraftServer.PlayerAttackedEntity).

**Comment by AtomicBlom** [comment]
Ah, cheers for the poke. 

It is actually fixed in the 1.0.0-alpha.x releases, but I forgot to promote them to release. I remembered I had to do it a few days ago and then forgot to actually do it again -_-

I'm at work right now, but I'll try remember to do it as soon as I get home.

**Comment by AtomicBlom** [comment]
Sorry for the late reply, I've scrounged up some time to do this.

They're still running on the alpha version of the types at 1.0.0-alpha.2, I hope to resolve that after a bunch of testing.
