### ISSUE TITLE
Figure out how to manage versioning against Minecraft.

### ISSUE THREAD

**Issue by AtomicBlom** [minecraft-addon-tools/generator-minecraft-addon#4]
Given that Scripting is now available in the release edition of Minecraft, it's important that users should be able to install release or beta versions of the bindings.

**Comment by misterflippy** [comment]
I'm not sure what the status is here, but I updated the javascript templates so they work with the 1.12 beta: https://github.com/misterflippy/generator-minecraft-addon/tree/1.12-beta.

**Comment by AtomicBlom** [comment]
Oh awesome.

Been a bit stuck updating the TypeScript definitions before I was going to start on this, but I'll try get it out asap
