### ISSUE TITLE
how to run script with vscode?

### ISSUE THREAD

**Issue by JinsX5** [minecraft-addon-tools/generator-minecraft-addon#5]
First i type ` npm install -g yo` in TERMINAL,It's succeed.

Then i use `yo minecraft-addon` and create file is succeesful.Below is feedback:
`? What will be the name of your addon? cdBedRock
? What will your addon do or provide? This is a test
? What namespace will you use? cdbedrock
? What kind of modules will make up the addon? Behaviors, Resources
? Will you be adding scripts? Yes
? What language do you want to script in? JavaScript
   create package.json
   create gulpfile.js
   create packs\resources\manifest.json
   create packs\resources\pack_icon.png
   create packs\behaviors\manifest.json
   create packs\behaviors\pack_icon.png
   create packs\behaviors\scripts\client\client.js
   create packs\behaviors\scripts\server\server.js
I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.`

Last,the question is when i use `C:\Users\pc\Desktop\testadd\cdBedRock> npm run installmod`
it's error feedback:
`npm ERR! missing script: installmod
npm ERR!
npm ERR! Did you mean this?
npm ERR!     installaddon

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\nodejs\node_cache\_logs\2019-03-20T21_13_19_165Z-debug.log`

I search the log but i can't find how to solve it,could you give me some clue?Thanks very much!

**Comment by AtomicBlom** [comment]
try `npm run installaddon`
early versions of the generator (or more specifically minecraft-addon-toolchain) used the term `installmod` but addon is more technically correct.

**Comment by JinsX5** [comment]
> try `npm run installaddon`
> early versions of the generator (or more specifically minecraft-addon-toolchain) used the term `installmod` but addon is more technically correct.

Thanks,its usefull.
