### ISSUE TITLE
Bug while creating addon

### ISSUE THREAD

**Issue by ghost** [minecraft-addon-tools/generator-minecraft-addon#9]
I chose to use "behaviour pack" module and then it says it's done and it's running npm install. It doesn't ask me to chose between javascript/typescript and it only creates 2 files:
package.json
gulpfile.js
So no "packs" folder.
I am using version 6.9.0(node js)

**Comment by misterflippy** [comment]
@mariglenpupa When you chose the behavior pack module, did you press "space" to select "Behaviors" or did you just press enter at the prompt?

I'm able to reproduce this behavior if I don't choose any module at all at the prompt.

It should look like this:
![image](https://user-images.githubusercontent.com/50192591/66343428-df7c8280-e908-11e9-807e-9fd63e6b58e8.png)

**Comment by ghost** [comment]
oh my bad mate... it works now thank you!
